apiVersion: apps/v1
kind: Deployment
metadata:
  name: asciiartify
  labels:
    app: asciiartify
spec:
<<<<<<< HEAD
  replicas: 1
=======
  replicas: 1
>>>>>>> 6a8e1f4 (AgroCD Pod Chandges)
  selector:
    matchLabels:
      app: asciiartify
  template:
    metadata:
      labels:
        app: asciiartify
    spec:
      containers:
      - name: asciiartify
        image: nginx:latest
        ports:
        - containerPort: 80
