apiVersion: apps/v1
kind: Deployment
metadata:
  name: asciiartify
  labels:
    app: asciiartify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asciiartify
  template:
    metadata:
      labels:
        app: asciiartify
    spec:
      containers:
        - name: asciiartify
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
